### PR TITLE
Full Pull Request

### PR DESCRIPTION
**Pull request by Programing-School**
Please Review 

Don't close it if there is a problem

### CODE REVIEW

**Comment by Programing-School** [comment]
@mudit023

**Comment by Programing-School** [comment]
Please Explain for me

I don't understand what do you mean with **PR** ?????????

**Comment by mudit023** [comment]
Don't make changes in all the files in one single PR. I closed it before because you have made changes in 34 different files, some of them don't require the change. Don't make any change in contribution.md readme file.

**Comment by mudit023** [comment]
> Please Explain for me
> 
> I don't understand what do you mean with **PR** ?????????

PR is Pull Request

**Comment by Programing-School** [comment]
Thanks

**Comment by mudit023** [comment]
Create different pull requests for different contributions so that I can merge them separately.

**Comment by Programing-School** [comment]
Ok

**Comment by Programing-School** [comment]
@mudit023 I added a pull request 

please approve

**Pull request closed without merging**
