### PR TITLE
Slider Profile Cards

### PR DESCRIPTION
**Pull request by Mahak008**
Here is the screenshot for the code.
Preview

### CODE REVIEW

**Review by Susaksham — CHANGES_REQUESTED** [review]
Add the comments and gif of the slider . Also add the css variable if requires.

**Comment by Mahak008** [comment]
> Add the comments in your code to explain it better to the template user and add a GIF of your template in your readme file. Also, add the CSS variables if required.

I am unable to record the gif .

**Comment by mudit023** [comment]
> > Add the comments in your code to explain it better to the template user and add a GIF of your template in your readme file. Also, add the CSS variables if required.
> 
> I am unable to record the gif .

Just add comments in your code. We'll take care of the gif.

**Comment by Mahak008** [comment]
> > > Add the comments in your code to explain it better to the template user and add a GIF of your template in your readme file. Also, add the CSS variables if required.
> > 
> > 
> > I am unable to record the gif .
> 
> Just add comments in your code. We'll take care of the gif.

I have added the comments kindly check it.

**Review by mudit023 — APPROVED** [review]
LGTM

**Pull request merged**
