### PR TITLE
Image Gallery Added

### PR DESCRIPTION
**Pull request by hamzailyas237**
I have added an image gallery template.

### CODE REVIEW

**Review by mudit023 — CHANGES_REQUESTED** [review]
- [ ] Add a proper readme file like [this](https://github.com/mudit023/templates/tree/main/animated-newsletter#readme)
- [ ] Add gifs of your template in the readme to show how it looks.

**Comment by hamzailyas237** [comment]
Please Accept my PR

**Comment by hamzailyas237** [comment]
@mudit023 I don't want to work on this issue more. I have added an image gallery. Merge my PR and raised another issue for the readme file so that any other can contribute to it. 
Than kyou.

**Comment by mudit023** [comment]
> @mudit023 I don't want to work on this issue more. I have added an image gallery. Merge my PR and raised another issue for the readme file so that any other can contribute to it. Thankyou.

Sorry but the PR will not be merged unless it follows our guidelines.

**Comment by hamzailyas237** [comment]
@mudit023 In the issue, firstly you just said to add image gallery and i added that. You don't asked about other things at that time, but if you don't want to merge it's okay 👍
Thank you.

**Comment by mudit023** [comment]
Everything is very clearly stated in the create new template issues #48  and also in [template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md)

**Comment by Programming-School-Pro-Coding** [comment]
Hello @mudit023 

Assign me

**Pull request closed without merging**
