### PR TITLE
Testimonials Section

### PR DESCRIPTION
**Pull request by Programing-School**

### CODE REVIEW

**Comment by Programing-School** [comment]
Hey @mudit023

**Comment by Programing-School** [comment]
Please Approve or mention me, do anything

**Comment by mudit023** [comment]
You don't need to tag me every time you create a Pull Request.

**Review by mudit023 — COMMENTED** [review]
Add Readme

**Comment by mudit023** [comment]
Create a new PR without updating this project's main readme. 
And add a readme in your template with screenshots.

**Comment by Programing-School** [comment]
> Create a new PR without updating this project's main readme. And add a readme in your template with screenshots.

**Comment by Programing-School** [comment]
> You don't need to tag me every time you create a Pull Request.

Ok I am sorry

**Pull request closed without merging**
