### PR TITLE
 Pricing Table

### PR DESCRIPTION
**Pull request by valeshgopal**
Added pricing table

### CODE REVIEW

**Review by Programming-School-Pro-Coding — APPROVED** [review]
Check this : https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md

**Comment by valeshgopal** [comment]
Added comments and css variables

**Review by Programming-School-Pro-Coding — APPROVED** [review]
LGTM

**Review by mudit023 — COMMENTED** [review]
LGTM

**Pull request merged**
