### PR TITLE
Profile_Card-9

### PR DESCRIPTION
**Pull request by ajay2827**
I have made a nice profile card.
I hope you will like it.

### CODE REVIEW

**Comment by Susaksham** [comment]
> I have made a nice profile card. I hope you will like it.

First you need to create an issue then we will assign you that issue than you will create a pull request

**Comment by Susaksham** [comment]
Also you need to add the comments , gif , readme , css variables stuff . follow our [!template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md)

**Review by mudit023 — CHANGES_REQUESTED** [review]
Do the required changes.

**Comment by ajay2827** [comment]
hii mudit, 
i have added readme.md

**Comment by Susaksham** [comment]
> hii mudit, i have added readme.md

You still have to add the gif rather than adding the couple of images , also add the css variables along with the comments in all files .

**Review by mudit023 — COMMENTED** [review]
- [ ] Add gif of your template in your readme file.
- [ ] Make use of CSS variables.

**Pull request closed without merging**
