### PR TITLE
Add stats counter widget

### PR DESCRIPTION
**Pull request by valeshgopal**
Added a widget that incrementally counts social media followers.

### CODE REVIEW

**Review by Programming-School-Pro-Coding — APPROVED** [review]
Very Amazing

**Review by mudit023 — COMMENTED** [review]
Add a readme file also with the screenshot of the template.

**Comment by valeshgopal** [comment]
Done!

**Review by Programming-School-Pro-Coding — APPROVED** [review]
LGTM

**Review by mudit023 — COMMENTED** [review]
LGTM

**Pull request merged**
