### PR TITLE
Drag and Drop

### PR DESCRIPTION
**Pull request by davidG999**

### CODE REVIEW

**Review by mudit023 — COMMENTED** [review]
Looks Good!

**Comment by mudit023** [comment]
Just add comments in your code and make use of CSS variables where you can. You can do it later and make another PR for it.

**Comment by mudit023** [comment]
Follow our [Template Guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md)

**Comment by davidG999** [comment]
Okay, will do

**Pull request merged**
