### PR TITLE
Portfolio Templates

### PR DESCRIPTION
**Pull request by Programming-School-Pro-Coding**
## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Template
- [ ] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Added to documentation?

- [ ] 📜 readme
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

### CODE REVIEW

**Comment by Programing-School** [comment]
Hey, How about this pull request ?

**Comment by mudit023** [comment]
@imRajAryan09 can you review this? Merge it if everything looks good.

**Comment by Programming-School-Pro-Coding** [comment]
Hey @pranavgoel29 and @imRajAryan09 please make anything about my PR

**Review by mudit023 — APPROVED** [review]
LGTM

**Pull request merged**
