### PR TITLE
Added Image-Carousel

### PR DESCRIPTION
**Pull request by AbhiMishra-Now**

### CODE REVIEW

**Review by mudit023 — COMMENTED** [review]
Thanks for the contribution. Can you add a small video of your carousle also in your Readme file?

**Comment by AbhiMishra-Now** [comment]
demo file added you can now merge it

**Review by mudit023 — APPROVED** [review]
Looks good, thanks for contributing!

**Comment by AbhiMishra-Now** [comment]
> Looks good, thanks for contributing!

✌🏼

**Pull request merged**
