### PR TITLE
Full Pull Request with New Templates and changes to issue #1

### PR DESCRIPTION
**Pull request by Programing-School**

### CODE REVIEW

**Comment by Programing-School** [comment]
Hey @mudit023 

Accept the pull request

**Comment by Programing-School** [comment]
> Screenshot should be added in the readme of every template. And you haven't added readme file to skills section template and theme toggle template.

I added the readme file in theme toggle

**Review by mudit023 — COMMENTED** [review]
Go through all the reviews I have made and create a new PR. Create a separate PR if you want to contribute to the [project readme](https://github.com/mudit023/templates/blob/main/Readme.md)

**Comment by Programing-School** [comment]
@mudit023 Please Add All of this code to the repository

**Pull request closed without merging**
