### PR TITLE
Make improvements to README.md

### PR DESCRIPTION
**Pull request by davidG999**
Fix typos and make other minor changes.

### CODE REVIEW

**Comment by Programing-School** [comment]
Hi @davidG999 
Are you online now ?

**Comment by davidG999** [comment]
> Hi @davidG999 
> Are you online now ?

I am now, yes. But writing on my phone

**Comment by Programing-School** [comment]
> > Hi @davidG999
> > Are you online now ?
> 
> I am now, yes. But writing on my phone

Ok

**Comment by Programing-School** [comment]
Please Contact me, What is your platform you want to contact me on ?

**Comment by davidG999** [comment]
> Please Contact me, What is your platform you want to contact me on ?

here's my Telegram: @SebastianTaburetkin

**Comment by Programing-School** [comment]
Ok

**Review by mudit023 — APPROVED** [review]
LGTM

**Pull request merged**
