### PR TITLE
Added MCQ-Quiz-App as a template

### PR DESCRIPTION
**Pull request by ashwin3005**
I have added a new template(MCQ-Quiz-App) made with HTML, CSS, and JavaScript.

### CODE REVIEW

**Comment by ashwin3005** [comment]
Add hacktoberfest-accepted label, If you like the template

**Comment by Programming-School-Pro-Coding** [comment]
Welcome Sir

Please some Screenshots of your App

**Review by Programming-School-Pro-Coding — CHANGES_REQUESTED** [review]
Please add A README File and read this guide to create a readme file: https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md

**Comment by ashwin3005** [comment]
Okay..

**Comment by ashwin3005** [comment]
now I have added README.md file.

**Comment by mudit023** [comment]
> now I have added README.md file.

Hey, thanks for the contribution. But you haven't added screenshots of your template in the Readme.

**Review by mudit023 — APPROVED** [review]
Thanks for the contribution✨

**Pull request merged**
